#!/bin/bash

# Quick Test Script for Logout & Error Pages

echo "🧪 Testing Logout & Error Pages"
echo "================================"
echo ""
echo "✅ LOGOUT FEATURE TEST STEPS:"
echo "1. Go to http://localhost:3000/login"
echo "   - Login with: john@example.com / password123"
echo ""
echo "2. Go to http://localhost:3000/ (homepage)"
echo "   - Check navbar shows 'Logout' link"
echo ""
echo "3. Click 'Logout' in navbar"
echo "   - EXPECT: Logout confirmation page"
echo "   - Should show: Your name, email, warning, two buttons"
echo ""
echo "4. Test CANCEL button"
echo "   - Click 'Cancel & Stay Logged In'"
echo "   - EXPECT: Redirect to homepage, still logged in"
echo "   - Navbar should still show 'Logout' (not 'Login')"
echo ""
echo "5. Click 'Logout' again"
echo "   - Now click 'Yes, Logout Now'"
echo "   - EXPECT: Success message, redirect to homepage"
echo "   - Navbar should show 'Login' (logged out)"
echo ""
echo "✅ 404 ERROR PAGE TEST:"
echo "1. Try invalid URL: http://localhost:3000/this-page-does-not-exist"
echo "   - EXPECT: 404 error page with:"
echo "     ✓ Error code '404'"
echo "     ✓ 'Page Not Found' message"
echo "     ✓ Helpful suggestions"
echo "     ✓ Links to go back (Homepage, Products)"
echo ""
echo "✅ 500 ERROR PAGE TEST:"
echo "1. This page shows when server error occurs"
echo "   - Normally triggered by bugs/exceptions"
echo "   - Shows error code '500'"
echo "   - Shows reassurance & support options"
echo ""
echo "================================"
echo "🎯 All tests should pass!"
echo ""
